
services:
  n8n:
    image: n8nio/n8n
    restart: always
    ports:
      - "5678:5678"
    environment:
      - N8N_SECURE_COOKIE=false
      - EXECUTIONS_DATA_PRUNE=true
      - EXECUTIONS_DATA_MAX_AGE=168
      - N8N_CORS_ALLOW_ORIGIN=http://127.0.0.1:5500
    volumes:
      - ./n8n-data:/home/node/.n8n
      - ./session-data:/data
    depends_on:
      - scraper

  scraper:
    build: ./scraper_service
    restart: always
    ports:
      - "8000:8000"
    environment:
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - ollama

  ollama:
    image: ollama/ollama
    restart: always
    # ports:
    #   - "11434:11434"
    volumes:
      - ollama_data:/root/.ollama

volumes:
  ollama_data:
